name: Trigger auto deployment for peerpulse

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/peerpulse-AutoDeployTrigger-bd9d0fce-1493-4f05-b5df-9ea333956baa.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PEERPULSE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: cabe093eced8acr.azurecr.io
          registryUsername: ${{ secrets.PEERPULSE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PEERPULSE_REGISTRY_PASSWORD }}
          containerAppName: peerpulse
          resourceGroup: peerpulse-rg
          imageToBuild: cabe093eced8acr.azurecr.io/peerpulse:${{ github.sha }}
