name: PostgreSQL service and tests
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
jobs:
  postgress-container-job:
    runs-on: ubuntu-latest
    container: node:20.10.0
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run prisma migrations
        run: npx prisma migrate dev --name init --preview-feature
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/postgres

      - name: Run tests
        run: npm test
        env:
          TEST_DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/postgres
